### ISSUE TITLE
V11 - v1.1.0 - Status Icon in not muting ping and volume control

### ISSUE THREAD

**Issue by Bekradan** [pplans/foundry-vtt-module-motion-tracker#62]
Hi Guys,

I know you have only just updated to V11, so thank you for all your hard work to date.

Just tried it and I think I have found a bug.  Status settings - enabling a status to mute the ping is having no effect.  I've tried changing it to a few others and still the same result.  

In addition, none of the volume sliders seem to work.  The volume is coming out at what appears full volume.  Muting completely does works.

Also tried Find the culprit in case its another module and even with all modules off other than motion tracker and the same issues are noted.  

If you need further info or testing just let me know.

**Comment by rdefendi** [comment]
I'm not the guy, but I mentioned it in the closed v11 issue when they pushed it out and the person who made the PR was pretty sure they knew how to fix it. Also, the ignore player buttons isn't working. I COULD get it to ignore players by setting their status to motionless. Anyway they said that we should make another issue and closed that one, so thanks for this one. :)

As a side note, an annoying but workable work-around to get a non-painful volume on the pings is to take the sounds in the Audiology and manually change the volume, then store them somewhere else and point the motion tracker there until this is resolved. That's what I did. I had to drop them each 25-35 db to get them to a place where I didn't think my players would complain. :)

**Comment by pplans** [comment]
Indeed I can reproduce it, it seems latest contributions broke it. Should had taken more time to review, I am fixing these, sound being very loud I suggest either the workaround proposed by rdefendi or to mute completely the audio, this one's still working

**Comment by pplans** [comment]
Hi guys, I've submitted the fixes, seems to work on my side, let me know if it works for you, I'll be more reactive since my campaign is being active anew starting this week. Cheers

**Comment by rdefendi** [comment]
Did you fix the bit he reported about enabling status not hiding an enemy? The behavior might have changed after your update too. I haven't been able to test this fully, but I think I saw it in the last five minutes of my prep today. I BELIEVE it only happens when the switch is turned to ignore PCs. I might have that backward, but I don't think so. If you ignore PCs, they disappear, but you can't make the xenos disappear by setting them motionless with a status. If you have the PC's set to appear, you can make everyone disappear by setting them motionless.

Which is my current workaround if I have that straight.

I'll test this better tomorrow during my lunchbreak game prep. Just found it too late today, but if someone wants to test it first, that's how I think it works.

**Comment by pplans** [comment]
I tried setting the invisible status, the dead status and the motionless status, also did a step by step debug to see what was happening and it was working. I might love to have a step by step with screenshots to fully understand what you mean if you can

**Comment by rdefendi** [comment]
Sure thing. I’ll test when I can tomorrow. As I said it’s the very last thing that happened so I’ll nail details down better.

**Comment by Bekradan** [comment]
Thank you!! Status icon now works as well as volume control.  I have though found another bug.  With 'scan other players' ticked on it works as it should.  With that flag turned off then it starts to ignore the status effect again of other tokens.  Not a deal breaker from my end, but thought you should know.

**Comment by pplans** [comment]
That's maybe what rdefendi was trying to explain to me, I'll take a look definitely :) thanks a lot guys

**Comment by rdefendi** [comment]
That IS indeed what I was trying to describe without ready access to my foundry to see all the feature names. :)

**Comment by pplans** [comment]
alright, I'll try to repro and find out what happened :) thanks lads

**Comment by pplans** [comment]
ok I see what's happening, I forgot that case yesterday it has been broken in the same way as the rest

**Comment by pplans** [comment]
I believe it is now fixed with update v1.1.2

**Comment by Bekradan** [comment]
pplans & rdefendi, thank you both for all your efforts.  Unfortunately, at least for me, the 'scan other players' is still not working regardless of the switch being on/off.  Players are still being picked up by the tracker.  Again not a deal breaker as I can just put status icon on for the players and it stops the ping.  Just to confirm I'm on v1.1.2.
Can't wait to use it on Sunday in my game as one of the players is Paul, mod dev for the Aliens-RPG system.  We have both been waiting for this to come back alive again so thank you.

**Comment by pplans** [comment]
lemme check I thought I tested that as well

**Comment by pplans** [comment]
are you certain these tokens belong to actors controlled by players ?

**Comment by rdefendi** [comment]
That's a great question. I'd test it but mine worked for five minutes and then broke as soon as I tried to log in as a player to see what happened from a player's POV. I mean broke almost completely. The motion tracker comes up but no animations fire off at all. They don't just fail to detect anything, I don't even see the pulse wave go off, it just fails from the get go and there's no errors in console. I was able to get it working briefly by rolling back to 1.1.1 and emptying my cache and resetting everything in the settings for the module to defaults, but it broke when I tried to upgrade to the new version again. And then I ran out of my hour lunch break of prep time and had to stop working on it. I'll grab my backup tonight so I don't overwrite it in the middle of the night, but it's REALLY broken on my machine right now.

**Comment by rdefendi** [comment]
I didn't have a character selected. Ignore me. I'm burned out. :)

**Comment by pplans** [comment]
haha no worries shit happen, I actually need to find a correct way to handle that case... Have no great ideas so far. Maybe I'll ask some friends at work, do you think we can close the Issue ?

**Comment by rdefendi** [comment]
Sure. Do we need to open another issue for the other problem? Attaching a character to an account doesn't exempt it from scanning for me.

I'm sure you've thought of this, but have you looked into setting it to whether the token is friendly, neutral, or hostile?

**Comment by pplans** [comment]
oh no then we can keep this issue here, but it seemed to work on my side, can you provide a step by step repro with all relevant information about the setup ? :-(

For other case, I'll admit that perhaps a while ago in the first days but decided not to do so because I didn't need it. But it's actually a good option, could you make another Issue for that ?

**Comment by rdefendi** [comment]
I was unclear. We can close this if you want me to open a ticket for the "Scan Other Players" issue. Which you do. And I have. So we can close this. I can mute l actors with status now regardless of the state of the "Scan Other Players" toggle. I tested that when submitting the other ticket.
